# Generated by Django 3.2.9 on 2021-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('imagenes', models.ImageField(upload_to='portafolio/imagenes/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
