# Generated by Django 3.2.9 on 2021-11-07 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('imagen', models.ImageField(upload_to='blog/images')),
                ('fecha', models.DateField(verbose_name=datetime.datetime(2021, 11, 7, 13, 32, 45, 657006))),
            ],
        ),
    ]
